name: TMAS Scan

on:
  push:

env:
  #FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: 'true'

jobs:
  tmas-scan:
    name: TMAS Repo Scan
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          path: repo-name

      - name: Build image
        run: docker build --tag my-nginx:ci ./repo-name

      - name: Download TMAS and Scan Repo for Open Source Vulnerabilities and Secrets
        uses: trendmicro/tmas-scan-action@v3.3.0
        with:
          version: '2' # Recommended: pin to major version for automatic updates within v2.x.x
          vulnerabilitiesScan: true
          malwareScan: false # Malware scanning is only available for container images at this time
          secretsScan: true
          artifact: 'docker:my-nginx:ci'
          additionalArgs: --region=eu-central-1
          tmasApiKey: ${{ secrets.TMAS_API_KEY }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload TMAS report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: tmas-report
          path: scan-report.md
          if-no-files-found: warn
